import { dollarsToCents } from "@/lib/money";
import type { BudgetPlan } from "@/lib/types/budget";
import {
  buildDefaultCategoryGroups,
  DEFAULT_TRACKING_ASSET_DEFS,
} from "@/lib/seed/default-templates";

const MONTH = "2026-08";

/**
 * Realistic college-student demo plan for EveryDollarFlow.
 * All money values are integer cents.
 * Defaults: simplified category groups + Brokerage/Retirement/HSA tracking assets.
 * No tracking liabilities by default.
 */
export function createDemoPlan(): BudgetPlan {
  const trackingAssets = DEFAULT_TRACKING_ASSET_DEFS.map((def, i) => ({
    id: def.id,
    name: def.name,
    type: def.type,
    kind: "tracking" as const,
    startingBalanceCents:
      def.id === "acct-brokerage"
        ? dollarsToCents(1000)
        : def.id === "acct-retirement"
          ? dollarsToCents(2500)
          : dollarsToCents(400),
    currency: "USD",
    institution: def.institution,
    closed: false,
    isHidden: false,
    sortOrder: 3 + i,
  }));

  return {
    id: "plan-demo-1",
    name: "Campus Life Plan",
    currency: "USD",
    workingMonthKey: MONTH,
    preferences: {
      hideBalances: false,
      timezone: "America/Chicago",
      currency: "USD",
      firstDayOfWeek: 0,
      enableTrackingLiabilities: false,
    },
    accounts: [
      {
        id: "acct-checking",
        name: "Checking",
        type: "checking",
        kind: "on_budget",
        startingBalanceCents: dollarsToCents(1300),
        currency: "USD",
        institution: "Campus Credit Union",
        lastFour: "4821",
        closed: false,
        isHidden: false,
        sortOrder: 0,
      },
      {
        id: "acct-hysa",
        name: "HYSA",
        type: "savings",
        kind: "on_budget",
        startingBalanceCents: dollarsToCents(2500),
        currency: "USD",
        institution: "Ally",
        lastFour: "9033",
        closed: false,
        isHidden: false,
        sortOrder: 1,
      },
      {
        id: "acct-cc",
        name: "Credit Card",
        type: "credit_card",
        kind: "credit",
        startingBalanceCents: dollarsToCents(-240),
        currency: "USD",
        institution: "Chase",
        lastFour: "1190",
        closed: false,
        isHidden: false,
        sortOrder: 2,
      },
      ...trackingAssets,
    ],
    categoryGroups: buildDefaultCategoryGroups(),
    categories: [
      {
        id: "cat-tithe",
        groupId: "grp-gifts",
        name: "Tithe",
        sortOrder: 0,
        hidden: false,
        rollover: true,
      },
      {
        id: "cat-car-insurance",
        groupId: "grp-bills",
        name: "Car Insurance",
        sortOrder: 0,
        hidden: false,
        rollover: true,
      },
      {
        id: "cat-phone",
        groupId: "grp-bills",
        name: "Phone",
        sortOrder: 1,
        hidden: false,
        rollover: true,
      },
      {
        id: "cat-tuition",
        groupId: "grp-education",
        name: "Tuition",
        sortOrder: 0,
        hidden: false,
        rollover: true,
      },
      {
        id: "cat-books",
        groupId: "grp-education",
        name: "Books",
        sortOrder: 1,
        hidden: false,
        rollover: true,
      },
      {
        id: "cat-gas",
        groupId: "grp-transport",
        name: "Gas",
        sortOrder: 0,
        hidden: false,
        rollover: true,
      },
      {
        id: "cat-travel",
        groupId: "grp-transport",
        name: "Travel",
        sortOrder: 1,
        hidden: false,
        rollover: true,
      },
      {
        id: "cat-groceries",
        groupId: "grp-food",
        name: "Groceries",
        sortOrder: 0,
        hidden: false,
        rollover: true,
        notes: "Weekly Aldi run",
      },
      {
        id: "cat-eating-out",
        groupId: "grp-food",
        name: "Eating Out",
        sortOrder: 1,
        hidden: false,
        rollover: true,
      },
      {
        id: "cat-personal",
        groupId: "grp-personal",
        name: "Personal Care",
        sortOrder: 0,
        hidden: false,
        rollover: true,
      },
      {
        id: "cat-mma",
        groupId: "grp-health",
        name: "MMA",
        sortOrder: 0,
        hidden: false,
        rollover: true,
      },
      {
        id: "cat-emergency",
        groupId: "grp-savings",
        name: "Emergency Fund",
        sortOrder: 0,
        hidden: false,
        rollover: true,
      },
      {
        id: "cat-investing",
        groupId: "grp-investments",
        name: "Investing",
        sortOrder: 0,
        hidden: false,
        rollover: true,
      },
      {
        id: "cat-fun-money",
        groupId: "grp-entertainment",
        name: "Fun Money",
        sortOrder: 0,
        hidden: false,
        rollover: true,
      },
      {
        id: "cat-cc-payment",
        groupId: "grp-bills",
        name: "Credit Card Payment",
        sortOrder: 2,
        hidden: false,
        rollover: true,
      },
    ],
    targets: [
      {
        id: "tgt-phone",
        name: "Phone",
        linkType: "category",
        categoryId: "cat-phone",
        accountId: null,
        type: "monthly_fixed",
        amountCents: dollarsToCents(45),
        dueDate: "2026-08-04",
      },
      {
        id: "tgt-car",
        name: "Car Insurance",
        linkType: "category",
        categoryId: "cat-car-insurance",
        accountId: null,
        type: "monthly_fixed",
        amountCents: dollarsToCents(110),
        dueDate: "2026-08-06",
      },
      {
        id: "tgt-groceries",
        name: "Groceries",
        linkType: "category",
        categoryId: "cat-groceries",
        accountId: null,
        type: "monthly_fixed",
        amountCents: dollarsToCents(280),
        dueDate: "2026-08-31",
      },
      {
        id: "tgt-mma",
        name: "MMA",
        linkType: "category",
        categoryId: "cat-mma",
        accountId: null,
        type: "monthly_fixed",
        amountCents: dollarsToCents(80),
        dueDate: "2026-08-09",
      },
      {
        id: "tgt-emergency",
        name: "Emergency Fund",
        linkType: "category",
        categoryId: "cat-emergency",
        accountId: null,
        type: "monthly_refill",
        amountCents: dollarsToCents(500),
        dueDate: "2026-12-31",
        notes: "Build to $500 available",
      },
      {
        id: "tgt-fun",
        name: "Fun Money",
        linkType: "category",
        categoryId: "cat-fun-money",
        accountId: null,
        type: "monthly_fixed",
        amountCents: dollarsToCents(60),
        dueDate: "2026-08-31",
      },
      {
        id: "tgt-travel",
        name: "Travel",
        linkType: "category",
        categoryId: "cat-travel",
        accountId: null,
        type: "target_by_date",
        amountCents: dollarsToCents(400),
        dueDate: "2026-08-05",
        notes: "Spring break buffer — due soon demo",
      },
      {
        id: "tgt-hysa-balance",
        name: "HYSA Balance",
        linkType: "account",
        categoryId: null,
        accountId: "acct-hysa",
        type: "reach_account_balance",
        amountCents: dollarsToCents(5000),
        notes: "Grow high-yield savings",
      },
      {
        id: "tgt-cc-payoff",
        name: "Credit Card Payoff",
        linkType: "account",
        categoryId: null,
        accountId: "acct-cc",
        type: "debt_payoff",
        amountCents: dollarsToCents(0),
        baselineAmountCents: dollarsToCents(240),
      },
    ],
    payees: [
      { id: "pay-employer", name: "Campus Bookstore Job" },
      { id: "pay-parents", name: "Family Support" },
      { id: "pay-aldi", name: "Aldi", defaultCategoryId: "cat-groceries" },
      { id: "pay-shell", name: "Shell", defaultCategoryId: "cat-gas" },
      { id: "pay-verizon", name: "Verizon", defaultCategoryId: "cat-phone" },
      {
        id: "pay-geico",
        name: "Geico",
        defaultCategoryId: "cat-car-insurance",
      },
      { id: "pay-dojo", name: "Iron Fist MMA", defaultCategoryId: "cat-mma" },
      {
        id: "pay-chipotle",
        name: "Chipotle",
        defaultCategoryId: "cat-eating-out",
      },
      { id: "pay-amazon", name: "Amazon", defaultCategoryId: "cat-books" },
      { id: "pay-church", name: "Local Church", defaultCategoryId: "cat-tithe" },
    ],
    monthlyBudgets: [
      { categoryId: "cat-tithe", monthKey: MONTH, assignedCents: dollarsToCents(120) },
      {
        categoryId: "cat-car-insurance",
        monthKey: MONTH,
        assignedCents: dollarsToCents(110),
      },
      { categoryId: "cat-phone", monthKey: MONTH, assignedCents: dollarsToCents(45) },
      {
        categoryId: "cat-tuition",
        monthKey: MONTH,
        assignedCents: dollarsToCents(200),
      },
      { categoryId: "cat-books", monthKey: MONTH, assignedCents: dollarsToCents(40) },
      { categoryId: "cat-gas", monthKey: MONTH, assignedCents: dollarsToCents(80) },
      {
        categoryId: "cat-groceries",
        monthKey: MONTH,
        assignedCents: dollarsToCents(280),
      },
      {
        categoryId: "cat-eating-out",
        monthKey: MONTH,
        assignedCents: dollarsToCents(40),
      },
      {
        categoryId: "cat-personal",
        monthKey: MONTH,
        assignedCents: dollarsToCents(25),
      },
      { categoryId: "cat-mma", monthKey: MONTH, assignedCents: dollarsToCents(80) },
      {
        categoryId: "cat-emergency",
        monthKey: MONTH,
        assignedCents: dollarsToCents(100),
      },
      {
        categoryId: "cat-investing",
        monthKey: MONTH,
        assignedCents: dollarsToCents(50),
      },
      { categoryId: "cat-travel", monthKey: MONTH, assignedCents: dollarsToCents(40) },
      {
        categoryId: "cat-fun-money",
        monthKey: MONTH,
        assignedCents: dollarsToCents(60),
      },
      {
        categoryId: "cat-cc-payment",
        monthKey: MONTH,
        assignedCents: dollarsToCents(100),
      },
    ],
    transactions: [
      {
        id: "txn-income-1",
        accountId: "acct-checking",
        date: "2026-08-01",
        payeeId: "pay-employer",
        payeeName: "Campus Bookstore Job",
        categoryId: null,
        memo: "Biweekly paycheck",
        amountCents: dollarsToCents(1450),
        cleared: "cleared",
        approved: true,
        isTransfer: false,
      },
      {
        id: "txn-income-2",
        accountId: "acct-checking",
        date: "2026-08-05",
        payeeId: "pay-parents",
        payeeName: "Family Support",
        categoryId: null,
        memo: "Monthly help",
        amountCents: dollarsToCents(300),
        cleared: "cleared",
        approved: true,
        isTransfer: false,
      },
      {
        id: "txn-tithe",
        accountId: "acct-checking",
        date: "2026-08-03",
        payeeId: "pay-church",
        payeeName: "Local Church",
        categoryId: "cat-tithe",
        amountCents: dollarsToCents(-120),
        cleared: "cleared",
        approved: true,
        isTransfer: false,
      },
      {
        id: "txn-phone",
        accountId: "acct-checking",
        date: "2026-08-04",
        payeeId: "pay-verizon",
        payeeName: "Verizon",
        categoryId: "cat-phone",
        amountCents: dollarsToCents(-45),
        cleared: "cleared",
        approved: true,
        isTransfer: false,
      },
      {
        id: "txn-insurance",
        accountId: "acct-checking",
        date: "2026-08-06",
        payeeId: "pay-geico",
        payeeName: "Geico",
        categoryId: "cat-car-insurance",
        amountCents: dollarsToCents(-110),
        cleared: "reconciled",
        approved: true,
        isTransfer: false,
      },
      {
        id: "txn-groceries-1",
        accountId: "acct-checking",
        date: "2026-08-07",
        payeeId: "pay-aldi",
        payeeName: "Aldi",
        categoryId: "cat-groceries",
        amountCents: dollarsToCents(-68.42),
        cleared: "cleared",
        approved: true,
        isTransfer: false,
      },
      {
        id: "txn-gas",
        accountId: "acct-checking",
        date: "2026-08-08",
        payeeId: "pay-shell",
        payeeName: "Shell",
        categoryId: "cat-gas",
        amountCents: dollarsToCents(-42.1),
        cleared: "cleared",
        approved: true,
        isTransfer: false,
      },
      {
        id: "txn-mma",
        accountId: "acct-checking",
        date: "2026-08-09",
        payeeId: "pay-dojo",
        payeeName: "Iron Fist MMA",
        categoryId: "cat-mma",
        amountCents: dollarsToCents(-80),
        cleared: "uncleared",
        approved: true,
        isTransfer: false,
      },
      {
        id: "txn-books",
        accountId: "acct-cc",
        date: "2026-08-10",
        payeeId: "pay-amazon",
        payeeName: "Amazon",
        categoryId: "cat-books",
        memo: "Used textbook",
        amountCents: dollarsToCents(-54.99),
        cleared: "cleared",
        approved: true,
        isTransfer: false,
      },
      // Overspent category: Eating Out assigned $40, spent $67.50
      {
        id: "txn-chipotle",
        accountId: "acct-checking",
        date: "2026-08-11",
        payeeId: "pay-chipotle",
        payeeName: "Chipotle",
        categoryId: "cat-eating-out",
        amountCents: dollarsToCents(-14.5),
        cleared: "cleared",
        approved: true,
        isTransfer: false,
      },
      {
        id: "txn-uber-eats",
        accountId: "acct-cc",
        date: "2026-08-12",
        payeeName: "Uber Eats",
        categoryId: "cat-eating-out",
        amountCents: dollarsToCents(-28),
        cleared: "cleared",
        approved: true,
        isTransfer: false,
      },
      {
        id: "txn-coffee",
        accountId: "acct-checking",
        date: "2026-08-13",
        payeeName: "Campus Cafe",
        categoryId: "cat-eating-out",
        amountCents: dollarsToCents(-25),
        cleared: "uncleared",
        approved: true,
        isTransfer: false,
      },
      {
        id: "txn-fun",
        accountId: "acct-checking",
        date: "2026-08-14",
        payeeName: "Bowling Alley",
        categoryId: "cat-fun-money",
        amountCents: dollarsToCents(-22),
        cleared: "cleared",
        approved: true,
        isTransfer: false,
      },
      // Transfer: Checking → HYSA (excluded from spending)
      {
        id: "txn-xfer-out",
        accountId: "acct-checking",
        date: "2026-08-15",
        payeeName: "Transfer to HYSA",
        categoryId: null,
        amountCents: dollarsToCents(-150),
        cleared: "cleared",
        approved: true,
        isTransfer: true,
        transferId: "xfer-1",
        transferPairId: "txn-xfer-in",
      },
      {
        id: "txn-xfer-in",
        accountId: "acct-hysa",
        date: "2026-08-15",
        payeeName: "Transfer from Checking",
        categoryId: null,
        amountCents: dollarsToCents(150),
        cleared: "cleared",
        approved: true,
        isTransfer: true,
        transferId: "xfer-1",
        transferPairId: "txn-xfer-out",
      },
      {
        id: "txn-groceries-2",
        accountId: "acct-checking",
        date: "2026-08-18",
        payeeId: "pay-aldi",
        payeeName: "Aldi",
        categoryId: "cat-groceries",
        amountCents: dollarsToCents(-72.18),
        cleared: "uncleared",
        approved: true,
        isTransfer: false,
      },
      {
        id: "txn-brokerage-gain",
        accountId: "acct-brokerage",
        date: "2026-08-20",
        payeeName: "Market Gain",
        categoryId: null,
        memo: "Unrealized — tracking only",
        amountCents: dollarsToCents(35),
        cleared: "cleared",
        approved: true,
        isTransfer: false,
      },
    ],
  };
}
